name: CI/CD - Tag on merge to master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 100
      - name: Get latest PR information
        uses: srt32/git-actions@v0.0.3
        with:
          args: echo "PULL=$(git config --global --add safe.directory /github/workspace ; git show --pretty='%h %s %d' $GITHUB_SHA --grep='Merge pull request' | head -n 1)" >> $GITHUB_ENV
      - name: Cancel if not PR
        if: ${{ env.PULL == '' }}
        run: exit 1
      - name: Get latest PR number
        run: echo "PR=$(echo $PULL | sed 's/.*Merge pull request \#//g' | cut -f1 -d' ')" >> $GITHUB_ENV
      - name: Set tag
        run: gh release create $(date "+%Y%m%d")-$PR --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}